ASPPIC.Public/ASPPIC.Public.Web/Controllers/CasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ASPPIC.Public.Business.Interfaces;
using ASPPIC.Public.Data.Gateways;
using Microsoft.AspNetCore.Mvc;

namespace ASPPIC.Public.Web.Controllers
{
    public class CasesController : Controller
    {
        private readonly ICountyService _countyService;

        public CasesController(ICountyService countyService)
        {
            _countyService = countyService;
        }
        public async Task<IActionResult> Index()
        {
            var result = await _countyService.GetDashboardInfo();
            return View(result);
        }
    }
}

ASPPIC.Public/ASPPIC.Public.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ASPPIC.Public.Business.Interfaces;
using ASPPIC.Public.Domain.Dtos;
using Microsoft.AspNetCore.Mvc;

namespace ASPPIC.Public.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ITutorialGroupService  _tutorialGroupService;

        public HomeController(ITutorialGroupService tutorialGroupService)
        {
            _tutorialGroupService = tutorialGroupService;
        }

        public async Task<IActionResult> Index()
        {
            var result = await _tutorialGroupService.Get();
            return View(result);
        }

        public IActionResult Rss()
        {
            return View();
        }        

        public async Task<IActionResult> CategoryDetails(Guid id)
        {
            var result = await _tutorialGroupService.Get(id);
            return View(result);
        }
    }
}

ASPPIC.Public/ASPPIC.Public.Web/Controllers/HospitalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ASPPIC.Public.Web.Controllers
{
    public class HospitalsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ASPPIC.Public/ASPPIC.Public.Web/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;

namespace ASPPIC.Public.Web.Controllers
{
    [EnableCors()]
    public class MapController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

ASPPIC.Public/ASPPIC.Public.Web/Views/Home/Index.cshtml
@model IEnumerable<ASPPIC.Public.Domain.Dtos.TutorialGroupDto>

    <div id="carouselExampleIndicators" class="carousel slide mb-5" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/images/1.png" alt="First slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Instruire</h5>
                    <p>Regulamente, informații de interes public și protocoale sanitare</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/images/2.png" alt="Second slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Raportare</h5>
                    <p>Informații la zi despre evoluția ratelor de infectare cu COVID-19</p>
                </div>
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/images/3.png" alt="Third slide">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Distribuție geografică</h5>
                    <p>Afișarea informațiilor privind răspândirea infectărilor cu COVID-19 pe baza informațiilor geografice</p>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
<div class="text-center">
    <h1 class="display-4">ASPPIC-19</h1>
    <h4>Abordări privind managementul sănătății publice în contextul pandemiei COVID-19</h4>
</div>

<div class="container pt-5 pb-3">

    <ul class="list-group">
        @foreach (var group in Model)
        {
        <li class="list-group-item">
            <h3><a href="@Url.Action("Category", "Information", new { id = group.Id })">@group.Name</a></h3>
            <hr />
            @Html.Raw(group.Description)
        </li>
        }
    </ul>
</div>
<style>
    .carousel-inner p,
    .carousel-inner h5 {
        text-shadow: 2px 2px black;
    }
</style>

ASPPIC.Public/ASPPIC.Public.Web/Views/Home/Rss.cshtml
<div class="container">
    <div class="row mb-5 text-center">
        <div class="col-md-12">
            <h1 class="text-center">Noutăți</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 mb-5">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h5 class="m-0">Comunicate de presă - Ministerul Sănătății</h5>
                </div>
                <div class="card-body">
                    <!-- start sw-rss-feed code -->
                    <script type="text/javascript">

                        rssfeed_url = new Array();
                        rssfeed_url[0] = "https://politepol.com/fd/codqqi7wLKPD";
                        rssfeed_frame_width = "100%";
                        rssfeed_frame_height = "400";
                        rssfeed_scroll = "on";
                        rssfeed_scroll_step = "6";
                        rssfeed_scroll_bar = "off";
                        rssfeed_target = "_blank";
                        rssfeed_font_size = "18";
                        rssfeed_font_face = "";
                        rssfeed_border = "off";
                        rssfeed_css_url = "";
                        rssfeed_title = "off";
                        rssfeed_title_name = "";
                        rssfeed_title_bgcolor = "#3366ff";
                        rssfeed_title_color = "#fff";
                        rssfeed_title_bgimage = "";
                        rssfeed_footer = "off";
                        rssfeed_footer_name = "rss feed";
                        rssfeed_footer_bgcolor = "#fff";
                        rssfeed_footer_color = "#333";
                        rssfeed_footer_bgimage = "";
                        rssfeed_item_title_length = "50";
                        rssfeed_item_title_color = "#666";
                        rssfeed_item_bgcolor = "#fff";
                        rssfeed_item_bgimage = "";
                        rssfeed_item_border_bottom = "on";
                        rssfeed_item_source_icon = "off";
                        rssfeed_item_date = "off";
                        rssfeed_item_description = "on";
                        rssfeed_item_description_length = "120";
                        rssfeed_item_description_color = "#666";
                        rssfeed_item_description_link_color = "#333";
                        rssfeed_item_description_tag = "off";
                        rssfeed_no_items = "0";
                        rssfeed_cache = "6bfdd17bdc0ced5ab376b7b673e4ad83";
                        //-->
                    </script>
                    <script type="text/javascript" src="//feed.surfing-waves.com/js/rss-feed.js"></script>

                </div>
            </div>
        </div>
        <div class="col-md-12 mb-5">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h5 class="m-0">INSP - noutăți COVID-19</h5>
                </div>
                <div class="card-body">
                    <!-- start sw-rss-feed code -->
                    <script type="text/javascript">

                        rssfeed_url = new Array();
                        rssfeed_url[0] = "https://politepol.com/fd/MNQ47ZRIPzgU";
                        rssfeed_frame_width = "100%";
                        rssfeed_frame_height = "400";
                        rssfeed_scroll = "on";
                        rssfeed_scroll_step = "6";
                        rssfeed_scroll_bar = "off";
                        rssfeed_target = "_blank";
                        rssfeed_font_size = "18";
                        rssfeed_font_face = "";
                        rssfeed_border = "off";
                        rssfeed_css_url = "";
                        rssfeed_title = "off";
                        rssfeed_title_name = "INSP - noutati covid";
                        rssfeed_title_bgcolor = "#3366ff";
                        rssfeed_title_color = "#fff";
                        rssfeed_title_bgimage = "";
                        rssfeed_footer = "off";
                        rssfeed_footer_name = "rss feed";
                        rssfeed_footer_bgcolor = "#fff";
                        rssfeed_footer_color = "#333";
                        rssfeed_footer_bgimage = "";
                        rssfeed_item_title_length = "50";
                        rssfeed_item_title_color = "#666";
                        rssfeed_item_bgcolor = "#fff";
                        rssfeed_item_bgimage = "";
                        rssfeed_item_border_bottom = "on";
                        rssfeed_item_source_icon = "off";
                        rssfeed_item_date = "off";
                        rssfeed_item_description = "on";
                        rssfeed_item_description_length = "120";
                        rssfeed_item_description_color = "#666";
                        rssfeed_item_description_link_color = "#333";
                        rssfeed_item_description_tag = "off";
                        rssfeed_no_items = "0";
                        rssfeed_cache = "4bfa64a895ccc34cc48017914282791d";
                        //-->
                    </script>
                    <script type="text/javascript" src="//feed.surfing-waves.com/js/rss-feed.js"></script>



                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 mb-5">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h5 class="m-0">INSP - situație la nivel global</h5>
                </div>
                <div class="card-body">
                    <!-- start sw-rss-feed code -->
                    <script type="text/javascript">

                        rssfeed_url = new Array();
                        rssfeed_url[0] = "https://politepol.com/fd/cOsyI5OGw26y ";
                        rssfeed_frame_width = "100%";
                        rssfeed_frame_height = "400";
                        rssfeed_scroll = "on";
                        rssfeed_scroll_step = "6";
                        rssfeed_scroll_bar = "off";
                        rssfeed_target = "_blank";
                        rssfeed_font_size = "18";
                        rssfeed_font_face = "";
                        rssfeed_border = "off";
                        rssfeed_css_url = "";
                        rssfeed_title = "off";
                        rssfeed_title_name = "INSP - Situatie la nivel global";
                        rssfeed_title_bgcolor = "#3366ff";
                        rssfeed_title_color = "#fff";
                        rssfeed_title_bgimage = "";
                        rssfeed_footer = "off";
                        rssfeed_footer_name = "rss feed";
                        rssfeed_footer_bgcolor = "#fff";
                        rssfeed_footer_color = "#333";
                        rssfeed_footer_bgimage = "";
                        rssfeed_item_title_length = "50";
                        rssfeed_item_title_color = "#666";
                        rssfeed_item_bgcolor = "#fff";
                        rssfeed_item_bgimage = "";
                        rssfeed_item_border_bottom = "on";
                        rssfeed_item_source_icon = "off";
                        rssfeed_item_date = "off";
                        rssfeed_item_description = "on";
                        rssfeed_item_description_length = "120";
                        rssfeed_item_description_color = "#666";
                        rssfeed_item_description_link_color = "#333";
                        rssfeed_item_description_tag = "off";
                        rssfeed_no_items = "0";
                        rssfeed_cache = "c0d5b3a6ed0efaa08d80c5b424f1e7fb";
                        //-->
                    </script>
                    <script type="text/javascript" src="//feed.surfing-waves.com/js/rss-feed.js"></script>



                </div>
            </div>
        </div>
        <div class="col-md-12 mb-5">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h5 class="m-0">INSP - Analiza cazuri confirmate COVID-19</h5>
                </div>
                <div class="card-body">
                    <!-- start sw-rss-feed code -->
                    <script type="text/javascript">

                        rssfeed_url = new Array();
                        rssfeed_url[0] = "https://politepol.com/fd/NUN4azYH5Ksz";
                        rssfeed_frame_width = "100%";
                        rssfeed_frame_height = "400";
                        rssfeed_scroll = "on";
                        rssfeed_scroll_step = "6";
                        rssfeed_scroll_bar = "off";
                        rssfeed_target = "_blank";
                        rssfeed_font_size = "18";
                        rssfeed_font_face = "";
                        rssfeed_border = "off";
                        rssfeed_css_url = "";
                        rssfeed_title = "off";
                        rssfeed_title_name = "INSP - Analiza cazuri confirmate COVID19";
                        rssfeed_title_bgcolor = "#3366ff";
                        rssfeed_title_color = "#fff";
                        rssfeed_title_bgimage = "";
                        rssfeed_footer = "off";
                        rssfeed_footer_name = "rss feed";
                        rssfeed_footer_bgcolor = "#fff";
                        rssfeed_footer_color = "#333";
                        rssfeed_footer_bgimage = "";
                        rssfeed_item_title_length = "50";
                        rssfeed_item_title_color = "#666";
                        rssfeed_item_bgcolor = "#fff";
                        rssfeed_item_bgimage = "";
                        rssfeed_item_border_bottom = "on";
                        rssfeed_item_source_icon = "off";
                        rssfeed_item_date = "off";
                        rssfeed_item_description = "on";
                        rssfeed_item_description_length = "120";
                        rssfeed_item_description_color = "#666";
                        rssfeed_item_description_link_color = "#333";
                        rssfeed_item_description_tag = "off";
                        rssfeed_no_items = "0";
                        rssfeed_cache = "c37a30515268ca78365c1778befb7c5a";
                                                //-->
                    </script>
                    <script type="text/javascript" src="//feed.surfing-waves.com/js/rss-feed.js"></script>



                </div>
            </div>
        </div>
    </div>
</div>

ASPPIC.Public/ASPPIC.Public.Web/Views/Hospitals/Index.cshtml
@{
    ViewData["Title"] = "Unități medicale";

}

<partial name="_HospitalModal" />
<partial name="_HospitalFilters" />
<div class="row">
    <div class="col-lg-2 col-md-3 col-sm-4">

    </div>
    <div class="col-lg-10 col-md-9 col-sm-8">

    </div>
</div>
<div class="map-container">
    <div id="map"></div>
</div>
@section Scripts {
    <style>

        html, body {
            display: -ms-flexbox !important;
            display: flex;
            min-height: 100vh;
            -ms-flex-direction: column;
            flex-direction: column;
        }

        body {
            margin: 0;
        }

        .fullscreen, main {
            display: -ms-flexbox !important;
            display: flex;
            -ms-flex-direction: column;
            flex-direction: column;
        }

        main {
            flex-grow: 1;
            padding: 0 !important;
        }

        .fullscreen {
            flex-grow: 1;
        }

        .map-container {
            display: -ms-flexbox !important;
            display: flex;
            -ms-flex-direction: column;
            flex-direction: column;
            flex-grow: 1;
            position: relative;
        }

        #map {
            position: absolute;
            left: 0;
            width: 100%;
            height: 100%;
        }

        footer {
            position: relative !important;
            bottom: auto !important;
        }

        .legendMarker {
            margin: 4px 15px 4px 5px;
            width: 15px;
        }

        .sidebar {
            z-index: 600;
            position: absolute;
            top: 87px;
            right: 30px;
        }

        @@media screen and (max-width: 1140px) {
            #collapseLegend {
                position: relative;
                left: auto;
                top: auto;
                bottom: auto;
                right: auto;
                margin: 0 0 15px 0;
            }
        }

        @@media screen and (min-width: 1141px) {
            #collapseLegend {
                display: block !important;
            }
        }

        /*.map-container {
            float: left;
            display: flex;
            flex-grow: 1;
            position: relative;
            display: -ms-flexbox;
            width: 100%;
        }

        #map {
            width: 100%;
            height: 1100px;
            position: absolute;
            left: 0px;
            top: 0px;
            outline: none;
        }*/
    </style>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/esri-leaflet@2.5.1/dist/esri-leaflet.js"
            integrity="sha512-q7X96AASUF0hol5Ih7AeZpRF6smJS55lcvy+GLWzJfZN+31/BQ8cgNx2FGF+IQSA4z2jHwB20vml+drmooqzzQ=="
            crossorigin=""></script>

    <script src="~/js/hospitals.js"></script>
}

ASPPIC.Public/ASPPIC.Public.Web/Views/Hospitals/_HospitalFilters.cshtml
<div class="text-center mb-3 d-xl-none">
    <button class="btn btn-outline-primary" type="button" data-toggle="collapse" data-target="#collapseLegend" aria-controls="collapseLegend">Legendă</button>
</div>
<div class="sidebar collapse" id="collapseLegend">
    <ul class="list-group">
        <li class="list-group-item">
            <h5 class="text-muted text-center">LEGENDĂ</h5>
        </li>
        <li class="list-group-item">
            @*<input type="checkbox" value="DSP" checked/>*@
            <img class="legendMarker" src='https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-yellow.png' />
            Direcție de Sănătate Publică
        </li>
        <li class="list-group-item">
            @*<input type="checkbox" value="TESTARE_COVID" checked/>*@
            <img class="legendMarker" src='https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-violet.png' />
            Centru de Testare COVID
        </li>
        <li class="list-group-item">
            @*<input type="checkbox" value="SUPORT_COVID" checked />*@
            <img class="legendMarker" src='https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-blue.png' />
            Unitate medicală suport COVID
        </li>
        <li class="list-group-item">
            @*<input type="checkbox" value="SUPORT_COVID_MATERNITATE" checked/>*@
            <img class="legendMarker" src='https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-gold.png' />
            Maternitate suport COVID
        </li>
        <li class="list-group-item">
            @*<input type="checkbox" value="SPITAL_FAZA_1" checked/>*@
            <img class="legendMarker" src='https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-orange.png' />
            Unitate medicală dedicată COVID - faza 1
        </li>
        <li class="list-group-item">
            @*<input type="checkbox" value="SPITAL_FAZA_2" checked/>*@
            <img class="legendMarker" src='https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-red.png' />
            Unitate medicală dedicată COVID - faza 2
        </li>
        <li class="list-group-item">
            @*<input type="checkbox" value="SUPORT_COVID_DIALIZA" checked />*@
            <img class="legendMarker" src='https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-green.png' />
            Centru de dializă suport COVID
        </li>
        <li class="list-group-item">
            @*<input type="checkbox" value="NON-COVID" checked/>*@
            <img class="legendMarker" src='https://raw.githubusercontent.com/pointhi/leaflet-color-markers/master/img/marker-icon-grey.png' />
            Unitate medicală NON-COVID
        </li>
    </ul>
</div>

ASPPIC.Public/ASPPIC.Public.Web/Views/Hospitals/_HospitalModal.cshtml
<div class="modal" id="hospitalModal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 id="hospitalModalTitle" class="modal-title"></h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-5">
                        <img id="hospitalImage" src="" class="img-fluid img-thumbnail" />
                    </div>
                    <div class="col-md-7">
                        <h5>Informații de contact</h5>
                        <p><b>Adresa: </b><span id="hospitalAddress"></span></p>
                        <p><b>E-mail: </b><span id="hospitalEmail"></span></p>
                        <p><b>Telefon: </b><span id="hospitalPhone"></span></p>
                        <p><b>Website: </b><a id="hospitalWebsite" href="#" target="_blank">#</a></p>
                        <p><b>Spital de stat:</b> <span id="stateHospital"></span></p>
                        <p><b>Indicații de orientare: </b><a id="hospitalRoute" href="#" target="_blank">Google Maps</a></p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <p><b>Alte informații:</b></p>
                        <p id="hospitalInfo"></p>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Închide</button>
            </div>
        </div>
    </div>
</div>

ASPPIC.Public/ASPPIC.Public.Web/Views/Information/Category.cshtml
@model ASPPIC.Public.Domain.Dtos.TutorialGroupDto

    <div class="container pt-5 pb-3">
        <h1 class="text-center pb-4">@Model.Name</h1>
        @Html.Raw(Model.Description)

    <ul class="list-group">
        @foreach (var item in Model.Tutorials)
        {
            <li class="list-group-item">
                <h4><a href="@Url.Action("Details", "Information", new { id = item.Id })">@item.Name</a></h4>
            </li>
            }
    </ul>
        
    </div>

ASPPIC.Public/ASPPIC.Public.Web/Views/Information/Details.cshtml
@model ASPPIC.Public.Domain.Dtos.TutorialDto

    <div class="container pt-5 pb-3">
        <h1 class="text-center pb-4">@Model.Name</h1>
        @Html.Raw(Model.Description)
    </div>

ASPPIC.Public/ASPPIC.Public.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ASPPIC-19</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false) 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASPPIC-19</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Informații</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cases" asp-action="Index">Situația infectărilor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="Index">Distribuție spațială</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hospitals" asp-action="Index">Unități medicale</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Rss">Noutăți</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid fullscreen">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ASPPIC-19
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>